# Generated by Django 2.0.3 on 2018-03-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('confederacion', models.CharField(max_length=40)),
                ('tecnico', models.CharField(max_length=40)),
                ('probabilidad', models.DecimalField(decimal_places=2, max_digits=11)),
                ('goles', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('grupo', models.CharField(max_length=40)),
            ],
        ),
    ]
