# Generated by Django 2.0.3 on 2018-03-31 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Seleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('confederacion', models.CharField(max_length=40)),
                ('tecnico', models.CharField(max_length=40)),
                ('probabilidad', models.DecimalField(decimal_places=2, max_digits=11, null=0)),
                ('ranking_fifa', models.IntegerField(null=0)),
                ('descripcion', models.CharField(max_length=200)),
                ('grupo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('puntuacion', models.DecimalField(decimal_places=2, max_digits=11, null=0)),
            ],
        ),
        migrations.AddField(
            model_name='partido',
            name='seleccion_ganadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ganadora_fk', to='seleccionesapi.Seleccion'),
        ),
        migrations.AddField(
            model_name='partido',
            name='seleccion_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_fk', to='seleccionesapi.Seleccion'),
        ),
        migrations.AddField(
            model_name='partido',
            name='seleccion_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante_fk', to='seleccionesapi.Seleccion'),
        ),
        migrations.AddField(
            model_name='partido',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_partido_fk', to='seleccionesapi.Tipo_Partido'),
        ),
    ]
