# Generated by Django 2.0.3 on 2018-03-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seleccionesapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seleccion',
            options={'ordering': ['probabilidad']},
        ),
        migrations.AddField(
            model_name='partido',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
