# Generated by Django 2.0.3 on 2018-03-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seleccionesapi', '0002_auto_20180331_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seleccion',
            name='confederacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seleccion',
            name='grupo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seleccion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seleccion',
            name='tecnico',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipo_partido',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
